### ISSUE TITLE
error: cannot find symbol import org.opencv.DocumentScannerPackage

### ISSUE THREAD

**Issue by prabhakaran8737** [Michaelvilleneuve/react-native-document-scanner#52]
![Screen Shot 2019-06-17 at 3 55 04 PM](https://user-images.githubusercontent.com/5249599/59597865-7504c400-9118-11e9-8310-ac34bdbeffe4.png)

This is my package.json file 

```
{
  "name": "TestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-document-scanner": "git+https://github.com/Michaelvilleneuve/react-native-document-scanner.git#android"
  },
  "devDependencies": {
    "babel-jest": "24.8.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

Was struggling for past 2 days.. unable to get any solutions.. I just installed using android branch and trying it in android mobile.

**Comment by Michaelvilleneuve** [comment]
The automatic linking seems to have failed retrieving the package name.
The import line should look like this :

import com.documentscanner.DocumentScannerPackage

**Comment by Sride** [comment]
@Michaelvilleneuve thanks for the response, you saved my day, after changing this line, the app shows blank white page. the app.js has only DocumentScanner

Here is the changed line.
```
import com.facebook.react.ReactApplication;
import com.documentscanner.DocumentScannerPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
```

**Comment by Michaelvilleneuve** [comment]
Did you ask for camera permissions, etc ?

**Comment by Sride** [comment]
@Michaelvilleneuve Yes it is...

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.scan" xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />

    <application 
      tools:replace="android:allowBackup" 
      android:name=".MainApplication" 
      android:label="@string/app_name" 
      android:icon="@mipmap/ic_launcher" 
      android:allowBackup="false" 
      android:theme="@style/AppTheme">

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

```

**Comment by ceyhuncfc9** [comment]
Hey @Sride, any update on this issue? I have the exact same problem.

**Comment by Sride** [comment]
Hey @ceyhuncfc9 Linking is the opencv is the problem,
refer this https://github.com/Michaelvilleneuve/react-native-perspective-image-cropper/issues/26

**Comment by Sride** [comment]
Hey @ceyhuncfc9 Linking opencv is the problem,
refer this Michaelvilleneuve/react-native-perspective-image-cropper#26
in this we have linked opencv.

**Comment by AGollapalli** [comment]
Looks like this is an issue with React Native's 60+ auto-linking. It looks like this, along with andreluisjunqueira/react-native-documentscanner-android need to be linked manually, following the instructions described in Junqueira's readme. 

To prevent auto-linking, create a file (if it doesn't already exist) called "react-native-config.js" and add the following:

` module.exports = {
  dependencies: {
    'react-native-documentscanner-android': {
      platforms: {
        android: null, // disable Android platform, other platforms will still autolink if provided
      },
    },
  },
};
`

**Comment by se09deluca** [comment]
Hi everyone, has anyone managed to make react-native-document-scanner work with react native 0.60.x on both platforms?
I succeeded on iOS but on Android even after having disabled auto linking, the only thing obtained is a black screen.
If someone did it, or met the same issues and passed, could he let me know how?

Hi @Sride, did you get react-native-document-scanner to work with zahidahmed024's suggestion?

Thank you in advance

**Comment by Sride** [comment]
Hi @se09deluca no react-native-document-scanner doesn't worked, i made work with react-native-perspective-image-cropper based on the zahidahmed024's suggestion.

**Comment by umutcetinkaya** [comment]
@Michaelvilleneuve  I'm having the same problem. I made the change as you said, but the problem was not solved?

**Comment by visw227** [comment]
HI I am getting the same problem, 
import org.opencv.DocumentScannerPackage; 
 error: cannot find symbol class DocumentScannerPackage

**Comment by Sride** [comment]
opencv is not installed properly, you need to install opencv manually. Here is the [source](https://drive.google.com/open?id=1sR21BRm_X1Z_vid8GSLJ2F_zMa0bV79l) that installed opencv. this is a package for react-native-perspective-image-cropper, you can use this to install react-native-document-scanner.

**Comment by visw227** [comment]
Sride, can I have your contact? Need your help

**Comment by visw227** [comment]
@Sride , I followed what you suggested.. I could run finally run the app with DocumentScanner (with no errors). But I'm getting a blanck white screen. My <DocumentScanner/> native component is not opening camera I gues!

**Comment by weinixuehao** [comment]
It is work to add react-native.config.js with below image content in this project root dir!
I have tested it

![image](https://user-images.githubusercontent.com/17869361/75607341-04c89200-5b31-11ea-91f8-b448d175f2f0.png)

**Comment by JB-CHAUVIN** [comment]
For me the solution was to add the open CV import before document-scanner's :

`include ':openCVLibrary310'
project(':openCVLibrary310').projectDir = new File(rootProject.projectDir,'../node_modules/react-native-document-scanner/android/openCVLibrary310')
include ':react-native-document-scanner'
project(':react-native-document-scanner').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-document-scanner/android')
`

**Comment by JB-CHAUVIN** [comment]
Same problem goes for me...

**Comment by RitanMihai** [comment]
Same here, with an extra error:
```
import org.opencv.RNCustomCropPackage;
                 ^
  symbol:   class RNCustomCropPackage
  location: package org.opencv
```

**Comment by neetigyachahar** [comment]
People struggling with a blank screen can try this: https://github.com/Michaelvilleneuve/react-native-document-scanner/issues/81#issuecomment-691935165

**Comment by nitin1039** [comment]
Hii @Michaelvilleneuve,
/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:41: error: cannot find symbol
import org.opencv.DocumentScannerPackage;
                 ^
  symbol:   class DocumentScannerPackage
  location: package org.opencv
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

I am getting this error, how can I solve it, In which file do I need to change, can you please tell me.
